version: '3.9'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - app-network

  backend:
    build:
      context: backend/ 
      dockerfile: Dockerfile2
    container_name: express-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://root:example@mongodb:27017/backend?authSource=admin
    depends_on:
      - mongodb
    networks:
      - app-network

  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile1  
    container_name: react-frontend
    ports:
      - "3001:80"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
